from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt
import pandas as pd

def create_professional_report(filename: str, report_data: dict, table_data: pd.DataFrame = None):
    """
    Creates a professional Word document with a title, multiple sections, and an optional data table.

    This function is designed for use by an agent to generate a dynamic report.
    It takes a dictionary for report content and a pandas DataFrame for tabular data.

    Args:
        filename: The name of the file to be saved (e.g., 'professional_report.docx').
        report_data: A dictionary containing the report's content, expected to have the
                     following structure:
                     {
                         "title": "Main Title",
                         "sections": [
                             {"heading": "Section 1 Heading", "body_text": "Paragraph text..."},
                             {"heading": "Section 2 Heading", "body_text": "More paragraph text..."}
                         ],
                         "footer": "Report generated by Agent"
                     }
        table_data: An optional pandas DataFrame to be included as a table in the report.
    """
    try:
        # Create a new Document object
        document = Document()

        # Add the main title (Level 0 heading)
        document.add_heading(report_data.get("title", "Generated Report"), level=0)

        # Iterate through the sections and add them to the document
        for section in report_data.get("sections", []):
            # Add a heading for the section (Level 1 heading)
            document.add_heading(section.get("heading", ""), level=1)
            # Add the body text for the section
            document.add_paragraph(section.get("body_text", ""))

        # Add a table if a pandas DataFrame is provided
        if table_data is not None and not table_data.empty:
            document.add_heading("Financial Data", level=2)
            # Add the column headers as the first row of the table
            table = document.add_table(rows=1, cols=len(table_data.columns))
            # Set table style for a professional look
            table.style = 'Table Grid'
            hdr_cells = table.rows[0].cells
            for i, column in enumerate(table_data.columns):
                hdr_cells[i].text = column
            
            # Add rows from the DataFrame
            for index, row in table_data.iterrows():
                row_cells = table.add_row().cells
                for i, cell_value in enumerate(row):
                    row_cells[i].text = str(cell_value)

        # Add a footer to the document
        if "footer" in report_data:
            section = document.sections[0]
            footer = section.footer
            paragraph = footer.paragraphs[0]
            paragraph.text = report_data["footer"]
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Save the document
        document.save(filename)
        print(f"Document '{filename}' created successfully.")

    except Exception as e:
        print(f"An error occurred while creating the document: {e}")

# --- Example Usage ---
# Define a dictionary with the report content
sample_report_data = {
    "title": "Quarterly Performance Review",
    "sections": [
        {
            "heading": "Market Summary",
            "body_text": (
                "The technology sector experienced a strong quarter, driven by robust "
                "demand for cloud computing and AI solutions. This trend has positively "
                "impacted the portfolio's overall performance. This section will detail "
                "the key drivers of this performance and provide a forward-looking outlook."
            )
        },
        {
            "heading": "Portfolio Holdings Analysis",
            "body_text": (
                "Our top holdings in the tech space, particularly in companies focused on "
                "enterprise software, showed significant gains. We will now present the "
                "specific performance data for these holdings in a table below."
            )
        }
    ],
    "footer": "Confidential Report | Generated by Asset Management AI"
}

# Create a sample pandas DataFrame (this could come from the yfinance function)
data = {
    'Date': ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04'],
    'Stock': ['AAPL', 'AAPL', 'MSFT', 'MSFT'],
    'Close Price': [180.50, 182.75, 295.10, 298.50],
    'Volume': [120000000, 115000000, 85000000, 90000000]
}
sample_table_data = pd.DataFrame(data)

# Specify the filename
document_filename = "professional_report.docx"

# Call the new function
create_professional_report(document_filename, sample_report_data, sample_table_data)
